### ISSUE TITLE
[Feat] ListItem component 제작

### ISSUE THREAD

**Issue by hyo-choi** [404-DriverNotFound/frontend-b#32]
## 기능에 대한 설명
친구 목록, 차단 목록, 업적 등에 공통으로 사용할 수 있는 container 컴포넌트를 제작합니다.

## 구현 상세 (Optional)
- [x] 컴포넌트 제작
- [x] Story 작성

## REFERENCE (Optional)
[Material UI Grid](https://material-ui.com/components/grid/)
[Material UI Card](https://material-ui.com/components/cards/)

**Comment by PennyBlack2008** [comment]
Grid와 Card를 어떻게 사용할 지 고민 중에 있습니다.

현재, Material-ui에 있는 코드 샘플을 보면서 비교하고 있는 데, 글자를 담는 것은 [Card](https://codesandbox.io/s/ndt9b?file=/demo.tsx)가 [Grid](https://codesandbox.io/s/8xv1h?file=/demo.tsx:1513-1728)보다 우월하다고 생각합니다.
왜냐하면, Grid를 클릭하셔서 코드샌드박스로 들어가시고, 오른쪽에 랜더링 창의 너비를 줄여보면 글자가 outline을 뚫고 옆으로 튀어나옵니다.
그러나, Card이 경우에는 창의 너비가 줄어든다고 글자가 outline을 뚫고 옆으로 튀어나오지는 않았습니다. 그래서 글자를 담을 때는 Card가 우월하니 글자를 담기위해선 Card를 사용해야한다고 생각합니다.

제가 Grid도 사용하게 될지는 모르겠지만, 지금까지 탐구해본 결과는 이렇습니다.

**Comment by PennyBlack2008** [comment]
좀 더 탐구해본 결과, 더 자세히 하면, Grid 차이와 Card의 차이가 아니라 Paper와 Grid를 함께 사용한 컴포넌트와 Card의 차이였고,
만약 Card 와 Grid를 사용해 Padding만 조정하면 되는 것이었는 데, 제가 너무 다르게 해석해서 생각습니다. 죄송합니다.

**Comment by PennyBlack2008** [comment]
1차 리뷰 후, 스토리 구현을 하고 있습니다.
- 친구목록의 친구 component 구현
- 하나의 채팅 component 구현
- 하나의 업적 component 구현
