### ISSUE TITLE
[Feat] 2FA Page 제작

### ISSUE THREAD

**Issue by hyo-choi** [404-DriverNotFound/frontend-b#36]
## 기능에 대한 설명
2FA를 진행하는 페이지를 제작한다.

## 구현 상세 (Optional)
- [x] 2FA 등록 Page 제작
- [x] 2FA 등록 Page story 작성
- [x] 2FA 인증 Page 제작
- [x] 2FA 인증 Page story 작성

## REFERENCE (Optional)
- [How to Fetch and Display an Image from an express backend server to a React js frontend?](https://stackoverflow.com/questions/57829529/how-to-fetch-and-display-an-image-from-an-express-backend-server-to-a-react-js-f)

**Comment by ykoh42** [comment]
내일은 작업할수 있게 오늘중에 끝내도록하겠읍니다.

**Comment by hyo-choi** [comment]
> 내일은 작업할수 있게 오늘중에 끝내도록하겠읍니다.

넵 수고 많으십니다! :)

**Comment by ykoh42** [comment]
폼데이터에서 true false로 넘어온 값을 처리 못해줘서.. 커밋을 못했습니다..

타입스크립트 버그인지 뭔지모르겠는데

boolean 타입의 변수를 typeof로 찍어보면 string으로 나오는 문제때문에 

저값을 특정 string과 비교를 못해서(타입이다르면 비교가안되네요..) 문제해결을 못하고있습니다.. 흑흑..

**Comment by ykoh42** [comment]
https://github.com/404-DriverNotFound/backend-b/tree/feat/Login-signup%237

요브랜치에서 작업했고, 급하게 마무리한 감이 있어서 충분한 테스트가 안되었을 수도 있는데, 수정할부분이 있으면 백엔드에 이슈남겨주세요!
