### ISSUE TITLE
[Fix] 로그인 이후 로그인 관련 페이지 경로로 접속하면 해당 페이지가 잠시 보이는 현상 개선

### ISSUE THREAD

**Issue by PennyBlack2008** [404-DriverNotFound/frontend-b#39]
## 문제점
현재 로그인 이후 주소창을 통해 로그인 관련 페이지 경로로 직접 이동하려 하면 해당 페이지가 잠시 보인 후 404 페이지로 이동합니다.
App 컴포넌트가 마운트될 때 무조건 세션, 본인 정보 API와 요청-응답하는 과정을 거치는데, 이 때 `userState.id`가 없는 상태를 잠시 거치기 때문에 이런 현상이 발생하는 것 같습니다.
기능상에 문제는 크게 없으나 UX 측면에서 의아할 수 있을 것 같아 수정이 필요해 보입니다.

## 예상되는(제대로 된) 동작
로그인 이후 주소창에 로그인 관련 페이지 주소를 입력해서 이동해도 해당 페이지가 보이지 않는다.

## 해결 방법 (optional)
- 유저 정보를 로컬스토리지 등에 저장해두는 방법?
  그런데 보안상 문제가 있을 것 같습니다.

## 버그 재현 방법 (버그를 발생시키는 방법)
1. 로그인 한다.
2. 주소창에 `localhost:3000/`, `localhost:3000/register`, `localhost:3000/register/2fa`, `localhost:3000/2fa`를 입력하여 접속한다.
3. 화면이 전환되는 것을 확인할 수 있다.

**Comment by hyo-choi** [comment]
프론트엔드 팀 회의 후 해당 이슈를 해결하려면 로그인 로직 자체를 변경하는 큰 수정을 가해야 한다는 결론을 내렸습니다. 그러나 새로고침을 하지 않는 이상 해당 현상이 발생하지 않고, 발생하더라도 크게 거슬리지 않는다는 쪽으로 팀 전체 의견이 통일되어 해당 이슈 해결은 하지 않기로 결정하였습니다.
따라서 본 이슈는 이 코멘트와 함께 close하겠습니다.
